#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define LOG_CONF_LEVEL_MAIN LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_NULLNET LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_FRAMER LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_6TOP LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_COAP LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_LWM2M LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_SYS LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_DTLS LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_SNMP LOG_LEVEL_NONE

#endif /* PROJECT_CONF_H_ */
